### ISSUE TITLE
线上部署结果

### ISSUE THREAD

**Issue by fengyunzaidushi** [yaakua/ai-outpainting-com#11]
![image](https://github.com/user-attachments/assets/8c3e971f-5599-440f-8cb2-ceb9bd1aef07)

**Comment by winjerry** [comment]
我也是这样，本地build后启动都没有问题

**Comment by yaakua** [comment]
重新拉取代码，然后删除本地node_modules和yarn.lock文件，并重新安装依赖即可，项目主页有更新说明。重新调整了语言文件在windows下的加载方式
